// Planning Home (/plans) — "My plans". English/Korean parity.
export const plansContent = {
  en: {
    eyebrow: 'Your planning space',
    title: 'My plans',
    intro: 'A place for the plans you build and keep. Start a plan, revisit one you saved, or head back to your path. Everything here stays on your device.',
    tools: {
      cashflow: { name: 'Cash Flow Planning', desc: 'Try a change to your monthly money and see the room it leaves.', start: 'Start a cash flow plan', startAnother: 'Start a new cash flow plan' },
      debt: { name: 'Debt Repayment', desc: 'Explore a different monthly payment for one debt and its tradeoff.', start: 'Start a debt plan', startAnother: 'Start a new debt plan' },
      emergency: { name: 'Emergency Fund', desc: 'See how much time the money you can reach could give you.', start: 'Start an emergency fund plan', startAnother: 'Start a new emergency fund plan' },
      goal: { name: 'Goal planning', desc: 'Explore where a steady monthly amount could take an education or personal goal.', start: 'Start a goal plan', startAnother: 'Start a new goal plan' },
      retirement: { name: 'Retirement planning', desc: 'Explore what a monthly contribution might become by the retirement point you enter, under assumptions you choose.', start: 'Start a retirement plan', startAnother: 'Start a new retirement plan' },
      insurance: { name: 'Protection planning', desc: 'Compare the responsibilities you want to protect with the protection resources you have or want to explore.', start: 'Start a protection plan', startAnother: 'Start a new protection plan' },
    },
    noneYet: 'No plan here yet.',
    debtCard: {
      title: 'Debt repayment plan',
      chosenByYou: 'Chosen by you',
      balance: 'Balance',
      currentPayment: 'Current payment',
      plannedPayment: 'Planned payment',
      currentPayoff: 'Est. payoff now',
      plannedPayoff: 'Est. payoff in plan',
      interestChange: 'Est. interest change',
      review: 'Review', edit: 'Edit', remove: 'Remove', openRoadmap: 'Open in Roadmap',
    },
    start: 'Start a cash flow plan',
    startAnother: 'Start a new cash flow plan',
    backToRoadmap: 'Back to your path',
    empty: {
      heading: 'No plans yet',
      body: 'A plan lets you try a change to your monthly money and keep it if it feels worth it. Nothing is saved until you choose to keep it.',
    },
    card: {
      title: 'Cash flow plan',
      chosenByYou: 'Chosen by you',
      sourceCheckup: 'Started from your check-up',
      sourcePlanning: 'Started from values you entered',
      changedHeading: 'What you changed',
      roomLine: 'Room left',
      gapLine: 'Short each month',
      totalChange: 'Total change',
      fresh: 'Matches your current check-up',
      stale: 'Based on an earlier check-up',
      review: 'Review',
      edit: 'Edit',
      remove: 'Remove',
      openRoadmap: 'Open in Roadmap',
      checkupPath: 'Go to your check-up',
    },
    emergencyCard: {
      title: 'Emergency fund plan',
      chosenByYou: 'Chosen by you',
      sourceCheckup: 'From your check-up picture',
      sourcePlanning: 'Values for this plan only',
      accessible: 'Money you can reach',
      mustPays: 'Monthly must-pays',
      months: 'Estimated months',
      monthsUnit: 'months',
      changeInMonths: 'Change in months',
      fresh: 'Matches your current check-up',
      stale: 'Based on an earlier check-up picture',
      review: 'Review', edit: 'Edit', remove: 'Remove', openRoadmap: 'Open in Roadmap', checkupPath: 'Go to your check-up',
    },
    goalCard: {
      title: 'Goal plan',
      educationName: 'Education',
      chosenByYou: 'Chosen by you',
      target: 'Target',
      months: 'Months to goal',
      setAside: 'Already set aside',
      contribution: 'Monthly contribution',
      projected: 'Projected at the goal',
      remainingGap: 'Remaining to target',
      aboveTarget: 'Above target',
      exactly: 'Exactly at target',
      progress: 'Projected progress',
      annualAssumption: 'Annual assumption',
      review: 'Review', edit: 'Edit', remove: 'Remove', openRoadmap: 'Open in Roadmap',
    },
    retirementCard: {
      title: 'Retirement plan',
      chosenByYou: 'Chosen by you',
      balance: 'Current balance',
      years: 'Years to retirement',
      contribution: 'Monthly contribution',
      annualReturn: 'Assumed annual return',
      projected: 'Projected balance',
      totalContrib: 'Total future contributions',
      growth: 'Estimated growth',
      employer: 'Employer monthly contribution',
      contribChange: 'Annual contribution change',
      inflation: 'Inflation assumption',
      inToday: 'In today\u2019s purchasing power',
      review: 'Review', edit: 'Edit', remove: 'Remove', openRoadmap: 'Open in Roadmap',
    },
    insuranceCard: {
      title: 'Protection plan',
      chosenByYou: 'Chosen by you',
      responsibilities: 'Total responsibilities',
      currentCoverage: 'Current coverage',
      exploredCoverage: 'Explored coverage',
      other: 'Other resources',
      uncovered: 'Amount not covered by the resources entered',
      none: 'No difference under these entries',
      beyond: 'Amount beyond the responsibilities entered',
      share: 'Share of the responsibilities entered',
      review: 'Review', edit: 'Edit', remove: 'Remove', openRoadmap: 'Open in Roadmap',
    },
  },
  ko: {
    eyebrow: '나의 계획 공간',
    title: '내 계획',
    intro: '당신이 만들고 간직하는 계획을 위한 곳이에요. 새 계획을 시작하거나, 저장한 계획을 다시 보거나, 로드맵으로 돌아갈 수 있어요. 여기 있는 모든 건 당신 기기에만 남아요.',
    tools: {
      cashflow: { name: '현금 흐름 계획', desc: '매달의 돈을 바꿔 보고 남는 여유를 살펴보세요.', start: '현금 흐름 계획 시작하기', startAnother: '새 현금 흐름 계획 시작하기' },
      debt: { name: '부채 상환', desc: '한 부채의 월 상환액을 다르게 해 그 맞바꿈을 살펴보세요.', start: '부채 계획 시작하기', startAnother: '새 부채 계획 시작하기' },
      emergency: { name: '비상금', desc: '지금 꺼내 쓸 수 있는 돈이 어느 정도의 시간을 줄 수 있는지 살펴보세요.', start: '비상금 계획 시작하기', startAnother: '새 비상금 계획 시작하기' },
      goal: { name: '목표 계획', desc: '매달 꾸준한 금액이 교육이나 개인 목표를 어디까지 데려갈 수 있는지 살펴보세요.', start: '목표 계획 시작하기', startAnother: '새 목표 계획 시작하기' },
      retirement: { name: '은퇴 계획', desc: '매달 넣는 금액이 입력한 은퇴 시점에 어느 정도가 될 수 있는지, 당신이 고른 가정 아래에서 살펴보세요.', start: '은퇴 계획 시작하기', startAnother: '새 은퇴 계획 시작하기' },
      insurance: { name: '보호 계획', desc: '지키고 싶은 책임과 지금 가진 또는 살펴보려는 보호자원을 비교해 보세요.', start: '보호 계획 시작하기', startAnother: '새 보호 계획 시작하기' },
    },
    noneYet: '아직 여기 계획이 없어요.',
    debtCard: {
      title: '부채 상환 계획',
      chosenByYou: '당신이 고른 것',
      balance: '잔액',
      currentPayment: '현재 상환액',
      plannedPayment: '계획 상환액',
      currentPayoff: '현재 예상 완납',
      plannedPayoff: '계획 예상 완납',
      interestChange: '예상 이자 변화',
      review: '다시 보기', edit: '수정', remove: '삭제', openRoadmap: '로드맵에서 열기',
    },
    start: '현금 흐름 계획 시작하기',
    startAnother: '새 현금 흐름 계획 시작하기',
    backToRoadmap: '내 길로 돌아가기',
    empty: {
      heading: '아직 계획이 없어요',
      body: '계획은 매달의 돈에 변화를 줘 보고, 가치 있게 느껴지면 간직하는 거예요. 저장하기로 정하기 전까지 아무것도 저장되지 않아요.',
    },
    card: {
      title: '현금 흐름 계획',
      chosenByYou: '당신이 고른 것',
      sourceCheckup: '체크업에서 시작함',
      sourcePlanning: '입력한 값에서 시작함',
      changedHeading: '바꾼 내용',
      roomLine: '남는 여유',
      gapLine: '매달 부족액',
      totalChange: '전체 변화',
      fresh: '지금 체크업과 일치해요',
      stale: '이전 체크업을 바탕으로 해요',
      review: '다시 보기',
      edit: '수정',
      remove: '삭제',
      openRoadmap: '로드맵에서 열기',
      checkupPath: '체크업으로 가기',
    },
    emergencyCard: {
      title: '비상금 계획',
      chosenByYou: '당신이 고른 것',
      sourceCheckup: '체크업 그림에서',
      sourcePlanning: '이 계획만을 위한 값',
      accessible: '꺼내 쓸 수 있는 돈',
      mustPays: '월 필수 지출',
      months: '예상 개월',
      monthsUnit: '개월',
      changeInMonths: '개월 변화',
      fresh: '현재 체크업과 일치',
      stale: '이전 체크업 그림 기준',
      review: '다시 보기', edit: '수정', remove: '삭제', openRoadmap: '로드맵에서 열기', checkupPath: '체크업으로 가기',
    },
    goalCard: {
      title: '목표 계획',
      educationName: '교육',
      chosenByYou: '당신이 고른 것',
      target: '목표금액',
      months: '목표까지 개월',
      setAside: '이미 모아둔 금액',
      contribution: '매달 넣는 금액',
      projected: '목표 시점 예상액',
      remainingGap: '목표까지 남은 금액',
      aboveTarget: '목표 초과액',
      exactly: '목표와 같음',
      progress: '예상 진행률',
      annualAssumption: '연간 가정',
      review: '다시 보기', edit: '수정', remove: '삭제', openRoadmap: '로드맵에서 열기',
    },
    retirementCard: {
      title: '은퇴 계획',
      chosenByYou: '당신이 고른 것',
      balance: '현재 잔액',
      years: '은퇴까지 연수',
      contribution: '매달 넣는 금액',
      annualReturn: '가정 연간 수익률',
      projected: '예상 잔액',
      totalContrib: '앞으로 넣을 총액',
      growth: '추정 증가분',
      employer: '고용주 월 적립액',
      contribChange: '연간 적립 변화율',
      inflation: '물가상승률 가정',
      inToday: '오늘의 구매력으로 본 금액',
      review: '다시 보기', edit: '수정', remove: '삭제', openRoadmap: '로드맵에서 열기',
    },
    insuranceCard: {
      title: '보호 계획',
      chosenByYou: '당신이 고른 것',
      responsibilities: '총 책임금액',
      currentCoverage: '현재 보장액',
      exploredCoverage: '살펴본 보장액',
      other: '다른 자원',
      uncovered: '입력한 보호자원으로 채워지지 않는 금액',
      none: '입력한 값에서는 차이가 없어요',
      beyond: '입력한 책임금액을 넘어서는 금액',
      share: '입력한 책임금액 대비 보호 비중',
      review: '다시 보기', edit: '수정', remove: '삭제', openRoadmap: '로드맵에서 열기',
    },
  },
}
