// Debt Repayment Planning Tool — copy. English/Korean parity. Natural product
// language (not textbook or professional-planner phrasing). Descriptive only.
export const debtContent = {
  en: {
    label: 'Explore a debt payment',
    purpose: 'See what could change if you chose a different monthly payment for one debt. This shows a tradeoff \u2014 it doesn\u2019t tell you what\u2019s best.',
    currencyChoice: { label: 'Currency for this plan', usd: 'US dollars ($)', krw: 'Korean won (\u20a9)' },
    fields: {
      balance: 'Current balance',
      apr: 'Annual interest rate (APR)',
      currentPayment: 'Current monthly payment',
      scenarioPayment: 'Monthly payment to explore',
    },
    fieldHelp: {
      balance: 'What you still owe on this one debt.',
      apr: 'The yearly rate, as a percent. Decimals are fine.',
      currentPayment: 'What you put toward this debt each month now.',
      scenarioPayment: 'A different monthly payment you\u2019d like to try.',
    },
    checkupRef: {
      label: 'For reference',
      note: (amount) => `Your check-up listed ${amount} as your total monthly debt payment. That may cover more than this one debt, so please enter this debt\u2019s payment yourself.`,
    },
    assumptions: {
      heading: 'What this estimate assumes',
      intro: 'To keep the numbers honest, this estimate assumes:',
      items: [
        'one debt only',
        'the interest rate stays the same',
        'you pay the same amount each month',
        'interest is added once a month',
        'no new charges on this debt',
        'no fees',
        'no missed or late payments',
        'one payment each month',
        'the last payment may be smaller than the rest',
      ],
      caveat: 'A lender\u2019s actual schedule may differ. This is an estimate to explore, not a promise.',
    },
    compare: {
      heading: 'Current and planned',
      currentPath: 'Current path',
      planPath: 'Plan you\u2019re exploring',
      currentPayment: 'Monthly payment now',
      plannedPayment: 'Planned monthly payment',
      paymentDiff: 'Monthly difference',
      payoff: 'Estimated time to pay off',
      interest: 'Estimated total interest',
      totalPaid: 'Estimated total paid',
      finalPayment: 'Smaller final payment',
      moreEachMonth: (amt) => `This plan asks for ${amt} more each month.`,
      lessEachMonth: (amt) => `This plan asks for ${amt} less each month.`,
      shorter: 'The estimated path is shorter.',
      longer: 'The estimated path is longer.',
      same: 'The estimated path is about the same length.',
      interestLess: (amt) => `Estimated interest is about ${amt} less.`,
      interestMore: (amt) => `Estimated interest is about ${amt} more.`,
      unavailable: 'Not available',
    },
    duration: { yr: 'yr', mo: 'mo', under1: 'under a month' },
    states: {
      zeroBalance: 'There\u2019s no remaining balance to model here.',
      zeroPayment: 'With no payment, the balance doesn\u2019t go down under these assumptions, so there\u2019s no payoff estimate.',
      belowInterest: 'This payment doesn\u2019t reduce the balance under these assumptions, so an estimated payoff time isn\u2019t available. You can try a different payment.',
      beyondLimit: 'The estimated payoff extends beyond what this tool can estimate (over 100 years), so an exact time isn\u2019t shown. You can try a different payment.',
      overflow: 'These numbers grow larger than this tool can safely display, so an estimate isn\u2019t shown. You can try smaller values.',
    },
    ratio: {
      heading: 'Payment share of income',
      line: (cur, plan) => `${cur} of monthly income now \u2192 ${plan} in this plan`,
      note: 'This just shows the payment as a share of income. It isn\u2019t a target.',
    },
    cashNote: {
      more: (amt) => `Heads up: the planned payment would use about ${amt} more of your monthly cash.`,
      less: (amt) => `The planned payment would free up about ${amt} of your monthly cash.`,
      caveat: 'Shown for context only \u2014 your check-up numbers aren\u2019t changed.',
    },
    reflection: 'What would this payment ask of your month? Would a shorter or longer path make things easier or harder for you? That part is yours to weigh.',
    keep: 'Keep this as my plan',
    reset: 'Reset',
    leave: 'Leave without saving',
    noChange: 'Choose a different monthly payment to explore a change worth keeping.',
    cantAdopt: 'This can be kept once both the current and planned payments have an estimated payoff time.',
    errors: {
      blank: 'Enter an amount.',
      negative: 'Enter zero or more.',
      nonNumeric: 'Enter a number.',
      decimalsUsd: 'Use at most two decimal places.',
      wholeKrw: 'Enter a whole amount, with no decimals.',
      tooLarge: 'That\u2019s larger than this tool can handle. Try a smaller number.',
      aprRange: 'Enter a yearly rate between 0 and 1000.',
      aprNonNumeric: 'Enter the rate as a number.',
    },
    confirm: {
      heading: 'Keep this plan?',
      line: (cur, plan) => `Change the monthly payment from ${cur} to ${plan}.`,
      yourChoice: 'This is the payment you chose to explore, not a FinE Companion recommendation.',
      confirm: 'Yes, keep it',
      cancel: 'Not yet',
      adopted: 'Saved to your plans. You can review, edit, or remove it any time.',
    },
    replace: { heading: 'Replace your current debt plan?', body: 'You already have a saved debt plan. Keeping this one will replace it.', confirm: 'Replace it', cancel: 'Keep the old one' },
    review: { heading: 'Your saved debt plan', note: 'This is the plan you kept. Nothing here changes it.', edit: 'Edit this plan', close: 'Close', backToPlans: 'Back to My plans' },
    edit: { heading: 'Editing your debt plan', note: 'Your saved plan stays as it is until you keep a new one.' },
  },
  ko: {
    label: '부채 상환 살펴보기',
    purpose: '한 가지 부채의 월 상환액을 다르게 하면 무엇이 달라지는지 살펴보세요. 이건 맞바꿈을 보여줄 뿐, 무엇이 최선인지 알려주지 않아요.',
    currencyChoice: { label: '이 계획의 통화', usd: '미국 달러 ($)', krw: '한국 원 (\u20a9)' },
    fields: {
      balance: '현재 잔액',
      apr: '연이자율 (APR)',
      currentPayment: '현재 월 상환액',
      scenarioPayment: '살펴볼 월 상환액',
    },
    fieldHelp: {
      balance: '이 부채로 아직 갚아야 할 금액이에요.',
      apr: '연 이자율(%)이에요. 소수점도 괜찮아요.',
      currentPayment: '지금 이 부채에 매달 넣는 금액이에요.',
      scenarioPayment: '한번 시도해 보고 싶은 다른 월 상환액이에요.',
    },
    checkupRef: {
      label: '참고',
      note: (amount) => `체크업에는 월 부채 상환액 합계가 ${amount}로 적혀 있어요. 이 금액은 다른 부채까지 포함할 수 있으니, 이 부채의 상환액은 직접 입력해 주세요.`,
    },
    assumptions: {
      heading: '이 추정이 가정하는 것',
      intro: '숫자가 정직하도록, 이 추정은 다음을 가정해요:',
      items: [
        '부채는 하나만',
        '이자율은 그대로 유지',
        '매달 같은 금액을 상환',
        '이자는 한 달에 한 번 붙음',
        '이 부채에 새 사용액 없음',
        '수수료 없음',
        '연체나 누락 없음',
        '한 달에 한 번 상환',
        '마지막 상환액은 더 적을 수 있음',
      ],
      caveat: '실제 대출 기관의 일정과는 다를 수 있어요. 이건 살펴보기 위한 추정이지 약속이 아니에요.',
    },
    compare: {
      heading: '현재와 계획',
      currentPath: '현재 경로',
      planPath: '살펴보는 계획',
      currentPayment: '현재 월 상환액',
      plannedPayment: '계획 월 상환액',
      paymentDiff: '월 차이',
      payoff: '예상 완납 기간',
      interest: '예상 총이자',
      totalPaid: '예상 총 상환액',
      finalPayment: '더 적은 마지막 상환액',
      moreEachMonth: (amt) => `이 계획은 매달 ${amt}을(를) 더 필요로 해요.`,
      lessEachMonth: (amt) => `이 계획은 매달 ${amt}을(를) 덜 필요로 해요.`,
      shorter: '예상 경로가 더 짧아져요.',
      longer: '예상 경로가 더 길어져요.',
      same: '예상 경로 길이는 비슷해요.',
      interestLess: (amt) => `예상 이자가 약 ${amt} 줄어요.`,
      interestMore: (amt) => `예상 이자가 약 ${amt} 늘어요.`,
      unavailable: '알 수 없음',
    },
    duration: { yr: '년', mo: '개월', under1: '한 달 미만' },
    states: {
      zeroBalance: '여기서 계산할 남은 잔액이 없어요.',
      zeroPayment: '상환액이 없으면 이 가정에서는 잔액이 줄지 않아, 완납 추정을 낼 수 없어요.',
      belowInterest: '이 상환액으로는 이 가정에서 잔액이 줄지 않아, 예상 완납 기간을 낼 수 없어요. 다른 금액을 시도해 볼 수 있어요.',
      beyondLimit: '예상 완납 기간이 이 도구가 추정할 수 있는 범위(100년 이상)를 넘어, 정확한 기간을 표시하지 않아요. 다른 금액을 시도해 볼 수 있어요.',
      overflow: '숫자가 이 도구가 안전하게 표시할 수 있는 범위보다 커져, 추정치를 보여줄 수 없어요. 더 작은 값을 시도해 볼 수 있어요.',
    },
    ratio: {
      heading: '소득 대비 상환액 비중',
      line: (cur, plan) => `현재 월 소득의 ${cur} \u2192 이 계획에서는 ${plan}`,
      note: '상환액을 소득의 비중으로 보여줄 뿐이에요. 목표 기준이 아니에요.',
    },
    cashNote: {
      more: (amt) => `참고: 계획 상환액은 매달 약 ${amt}의 현금을 더 쓰게 돼요.`,
      less: (amt) => `계획 상환액은 매달 약 ${amt}의 현금을 남겨 줘요.`,
      caveat: '맥락을 위한 표시일 뿐 \u2014 체크업 숫자는 바뀌지 않아요.',
    },
    reflection: '이 상환액은 당신의 한 달에 무엇을 요구할까요? 더 짧거나 더 긴 경로가 당신에게 무엇을 쉽게 또는 어렵게 만들까요? 그건 당신이 저울질할 몫이에요.',
    keep: '이걸 내 계획으로 저장',
    reset: '되돌리기',
    leave: '저장하지 않고 나가기',
    noChange: '간직할 만한 변화를 보려면 다른 월 상환액을 골라 보세요.',
    cantAdopt: '현재와 계획 상환액 모두 예상 완납 기간이 나올 때 저장할 수 있어요.',
    errors: {
      blank: '금액을 넣어 주세요.',
      negative: '0 이상 넣어 주세요.',
      nonNumeric: '숫자를 넣어 주세요.',
      decimalsUsd: '소수점은 두 자리까지만 넣어 주세요.',
      wholeKrw: '소수점 없이 정수 금액을 넣어 주세요.',
      tooLarge: '이 도구가 다룰 수 있는 값보다 커요. 더 작은 숫자를 넣어 주세요.',
      aprRange: '연이자율을 0에서 1000 사이로 넣어 주세요.',
      aprNonNumeric: '이자율을 숫자로 넣어 주세요.',
    },
    confirm: {
      heading: '이 계획을 저장할까요?',
      line: (cur, plan) => `월 상환액을 ${cur}에서 ${plan}(으)로 바꿔요.`,
      yourChoice: '이건 당신이 살펴보려고 고른 상환액이에요. FinE Companion의 추천이 아니에요.',
      confirm: '네, 저장할게요',
      cancel: '아직요',
      adopted: '내 계획에 저장됐어요. 언제든 다시 보거나, 수정하거나, 삭제할 수 있어요.',
    },
    replace: { heading: '지금 부채 계획을 바꿀까요?', body: '이미 저장된 부채 계획이 있어요. 이걸 저장하면 그 계획을 대신해요.', confirm: '바꿀게요', cancel: '기존 것 유지' },
    review: { heading: '저장된 부채 계획', note: '당신이 저장한 계획이에요. 여기서는 아무것도 바뀌지 않아요.', edit: '이 계획 수정', close: '닫기', backToPlans: '내 계획으로 돌아가기' },
    edit: { heading: '부채 계획 수정 중', note: '새로 저장하기 전까지 기존 계획은 그대로예요.' },
  },
}
