// Emergency Fund Planning Tool — copy. EN/KO parity. Natural product language,
// descriptive only. No target, benchmark, state label, or recommended months.
export const emergencyContent = {
  en: {
    label: 'Emergency fund',
    purpose: 'See how much time the money you can reach could give you if life were interrupted. This is a way to explore your own situation \u2014 not a target or a grade.',
    currencyChoice: { label: 'Currency for this plan', usd: 'US dollars ($)', krw: 'Korean won (\u20a9)' },
    source: {
      choose: 'Where should this plan start?',
      fromCheckup: 'Start from your check-up picture',
      fromCheckupHint: 'Uses the accessible savings and monthly must-pays you already shared.',
      planning: 'Enter values just for this plan',
      planningHint: 'Nothing here is saved to your check-up.',
      checkupCaption: 'From your check-up picture',
      planningCaption: 'Values for this plan only',
      beginsFrom: 'This plan begins from the same accessible money and monthly must-pays from your check-up.',
      planningNote: 'These values are used only for this plan and are not saved to your check-up.',
    },
    fields: {
      accessible: 'Money you can reach quickly',
      mustPays: 'Monthly costs that must continue',
    },
    fieldHelp: {
      accessible: 'Savings you could use right away if income paused.',
      mustPays: 'The essentials and debt payments that keep going each month.',
    },
    scenarioFields: {
      accessible: 'Planned money you can reach',
      mustPays: 'Planned monthly must-pays',
    },
    baselineContinue: 'Continue',
    baselineHeading: 'Your starting values',
    assumptions: 'This estimate assumes the money you can reach and your monthly must-pays stay as entered, and that those costs continue each month.',
    compare: {
      heading: 'Now and planned',
      accessible: 'Money you can reach',
      mustPays: 'Monthly must-pays',
      months: 'Estimated months of room',
      now: 'Now',
      planned: 'Planned',
      changeInMonths: 'Change in months',
      changed: 'changed',
      unchanged: 'unchanged',
      more: 'That is more time of accessible room.',
      less: 'That is less time of accessible room.',
      same: 'The estimated time is about the same.',
    },
    monthsUnit: 'months',
    states: {
      unavailable: 'A monthly time estimate needs costs that continue above zero. You can still adjust the amounts.',
      beyondLimit: 'This is beyond the range this tool can display, so an exact number isn\u2019t shown. You can still adjust the amounts.',
    },
    meaning: 'This estimate shows how much time the accessible money could create under the monthly costs entered. The point is not the number itself, but the room it may give you to keep your choices open.',
    adequacy: 'There is no single number that fits every life. This estimate is a way to explore your own situation, not a grade or finish line.',
    keep: 'Keep this as my plan',
    reset: 'Reset',
    leave: 'Leave without saving',
    noChange: 'Adjust the money you can reach or your monthly must-pays to explore a change worth keeping.',
    cantAdopt: 'This can be kept once the plan produces a valid month estimate that differs from where it started.',
    errors: {
      blank: 'Enter an amount.',
      negative: 'Enter zero or more.',
      nonNumeric: 'Enter a number.',
      decimalsUsd: 'Use at most two decimal places.',
      wholeKrw: 'Enter a whole amount, with no decimals.',
      tooLarge: 'That\u2019s larger than this tool can handle. Try a smaller number.',
    },
    confirm: {
      heading: 'Keep this plan?',
      line: (a, b) => `Change the estimated room from ${a} to ${b}.`,
      yourChoice: 'This is the scenario you chose to explore, not a FinE Companion recommendation.',
      confirm: 'Yes, keep it',
      cancel: 'Not yet',
      adopted: 'Saved to your plans. You can review, edit, or remove it any time.',
    },
    replace: { heading: 'Replace your current emergency fund plan?', body: 'You already have a saved emergency fund plan. Keeping this one will replace it.', confirm: 'Replace it', cancel: 'Keep the old one' },
    review: { heading: 'Your saved emergency fund plan', note: 'This is the plan you kept. Nothing here changes it.', edit: 'Edit this plan', backToPlans: 'Back to My plans', close: 'Close' },
    edit: { heading: 'Editing your emergency fund plan', note: 'Your saved plan stays as it is until you keep a new one.' },
    stale: 'Based on an earlier check-up picture. Editing will use your current picture.',
    staleUneditable: 'Based on an earlier check-up picture. Review your check-up before editing this plan.',
    checkupPath: 'Go to your check-up',
  },
  ko: {
    label: '비상금',
    purpose: '삶이 잠시 멈췄을 때, 지금 꺼내 쓸 수 있는 돈이 어느 정도의 시간을 줄 수 있는지 살펴보세요. 이건 내 상황을 살펴보기 위한 것이지 목표나 점수가 아니에요.',
    currencyChoice: { label: '이 계획의 통화', usd: '미국 달러 ($)', krw: '한국 원 (\u20a9)' },
    source: {
      choose: '이 계획을 어디서 시작할까요?',
      fromCheckup: '체크업 그림에서 시작하기',
      fromCheckupHint: '이미 알려준 꺼내 쓸 수 있는 저축과 매달 꼭 나가는 비용을 사용해요.',
      planning: '이 계획만을 위한 값 입력하기',
      planningHint: '여기 입력한 건 체크업에 저장되지 않아요.',
      checkupCaption: '체크업 그림에서',
      planningCaption: '이 계획만을 위한 값',
      beginsFrom: '이 계획은 체크업의 꺼내 쓸 수 있는 돈과 매달 꼭 나가는 비용에서 시작해요.',
      planningNote: '이 값은 이 계획에만 쓰이고 체크업에 저장되지 않아요.',
    },
    fields: {
      accessible: '빨리 꺼내 쓸 수 있는 돈',
      mustPays: '계속 나가야 하는 월 비용',
    },
    fieldHelp: {
      accessible: '소득이 멈추면 바로 쓸 수 있는 저축이에요.',
      mustPays: '매달 계속 나가는 필수 지출과 부채 상환이에요.',
    },
    scenarioFields: {
      accessible: '계획한 꺼내 쓸 수 있는 돈',
      mustPays: '계획한 월 필수 지출',
    },
    baselineContinue: '계속',
    baselineHeading: '시작 값',
    assumptions: '이 추정은 꺼내 쓸 수 있는 돈과 월 필수 지출이 입력한 대로 유지되고, 그 비용이 매달 계속된다고 가정해요.',
    compare: {
      heading: '지금과 계획',
      accessible: '꺼내 쓸 수 있는 돈',
      mustPays: '월 필수 지출',
      months: '예상 여유 개월',
      now: '지금',
      planned: '계획',
      changeInMonths: '개월 변화',
      changed: '바뀜',
      unchanged: '그대로',
      more: '꺼내 쓸 수 있는 여유 시간이 더 늘어요.',
      less: '꺼내 쓸 수 있는 여유 시간이 더 줄어요.',
      same: '예상 시간은 비슷해요.',
    },
    monthsUnit: '개월',
    states: {
      unavailable: '몇 개월의 여유인지 보려면 계속 나가는 비용이 0보다 커야 해요. 금액은 계속 조정해볼 수 있어요.',
      beyondLimit: '이 도구가 표시할 수 있는 범위를 넘어, 정확한 숫자를 보여줄 수 없어요. 금액은 계속 조정해볼 수 있어요.',
    },
    meaning: '이 값은 입력한 월 지출을 기준으로 지금 꺼내 쓸 수 있는 돈이 어느 정도의 시간을 만들어줄 수 있는지 보여줘요. 중요한 것은 숫자 자체보다 그 시간이 선택할 여유를 지켜줄 수 있다는 점이에요.',
    adequacy: '모든 사람에게 맞는 하나의 숫자는 없어요. 이 값은 내 상황을 살펴보기 위한 것이지 점수나 합격선이 아니에요.',
    keep: '이걸 내 계획으로 저장',
    reset: '되돌리기',
    leave: '저장하지 않고 나가기',
    noChange: '간직할 만한 변화를 보려면 꺼내 쓸 수 있는 돈이나 월 필수 지출을 조정해 보세요.',
    cantAdopt: '시작한 값과 다른 유효한 개월 추정이 나올 때 저장할 수 있어요.',
    errors: {
      blank: '금액을 넣어 주세요.',
      negative: '0 이상 넣어 주세요.',
      nonNumeric: '숫자를 넣어 주세요.',
      decimalsUsd: '소수점은 두 자리까지만 넣어 주세요.',
      wholeKrw: '소수점 없이 정수 금액을 넣어 주세요.',
      tooLarge: '이 도구가 다룰 수 있는 값보다 커요. 더 작은 숫자를 넣어 주세요.',
    },
    confirm: {
      heading: '이 계획을 저장할까요?',
      line: (a, b) => `예상 여유를 ${a}에서 ${b}(으)로 바꿔요.`,
      yourChoice: '이건 당신이 살펴보려고 고른 시나리오예요. FinE Companion의 추천이 아니에요.',
      confirm: '네, 저장할게요',
      cancel: '아직요',
      adopted: '내 계획에 저장됐어요. 언제든 다시 보거나, 수정하거나, 삭제할 수 있어요.',
    },
    replace: { heading: '지금 비상금 계획을 바꿀까요?', body: '이미 저장된 비상금 계획이 있어요. 이걸 저장하면 그 계획을 대신해요.', confirm: '바꿀게요', cancel: '기존 것 유지' },
    review: { heading: '저장된 비상금 계획', note: '당신이 저장한 계획이에요. 여기서는 아무것도 바뀌지 않아요.', edit: '이 계획 수정', backToPlans: '내 계획으로 돌아가기', close: '닫기' },
    edit: { heading: '비상금 계획 수정 중', note: '새로 저장하기 전까지 기존 계획은 그대로예요.' },
    stale: '이전 체크업 그림을 기준으로 해요. 수정하면 현재 그림을 사용해요.',
    staleUneditable: '이전 체크업 그림을 기준으로 해요. 이 계획을 수정하려면 먼저 체크업을 다시 살펴보세요.',
    checkupPath: '체크업으로 가기',
  },
}
