// Goal / Education Planning Tool — copy. EN/KO parity. Descriptive only: no
// target recommendation, no investment, no realistic/unrealistic judgment, no grade.
export const goalContent = {
  en: {
    label: 'Goal planning',
    purpose: 'If you keep setting aside an amount each month, see where you could be by the time your goal arrives. This is a way to explore your own plan \u2014 not a target, a recommendation, or a judgment about the goal.',
    currencyChoice: { label: 'Currency for this plan', usd: 'US dollars ($)', krw: 'Korean won (\u20a9)' },
    type: {
      heading: 'What is this goal?',
      education: 'Education',
      custom: 'Another goal',
      nameLabel: 'Name this goal',
      namePlaceholder: 'e.g. New car, Home deposit',
      educationName: 'Education',
    },
    fields: {
      target: 'Target amount',
      setAside: 'Amount already set aside',
      months: 'Months until the goal',
      currentContribution: 'Current monthly contribution',
      plannedContribution: 'Monthly contribution to explore',
    },
    fieldHelp: {
      target: 'The future amount you\u2019re aiming for.',
      setAside: 'What you\u2019ve saved toward this goal so far.',
      months: 'A whole number of months from now.',
      currentContribution: 'What you set aside for this goal each month now.',
      plannedContribution: 'A monthly amount you\u2019d like to try.',
    },
    assumptionsHeading: 'What this estimate assumes',
    assumptions: [
      'no investment return',
      'no interest',
      'no inflation adjustment',
      'no taxes or fees',
      'no withdrawals',
      'one contribution each month',
      'the target is the future amount you chose',
      'actual life and costs may change',
    ],
    assumptionsActive: [
      'a constant annual return or interest assumption you entered',
      'the annual rate is converted to an equivalent monthly rate',
      'the return is applied before the end-of-month contribution',
      'actual returns can vary and may be negative',
      'no inflation adjustment',
      'no taxes or fees',
      'no withdrawals',
      'one contribution each month',
      'the target is the future amount you chose',
      'actual life and costs may change',
    ],
    optional: {
      heading: 'Adjust with optional assumptions',
      help: 'Add only the assumptions you want to explore. You can keep the simple estimate without changing anything here.',
      optIn: 'Include an annual return or interest assumption',
      field: 'Annual return or interest assumption',
      fieldHelp: 'This is a value you choose to explore, not an expected or recommended return.',
      applied: 'Annual return or interest assumption applied',
      uncertainty: 'The adjusted amounts are estimates under the annual assumption entered here. They are not forecasts or promised results, and actual returns may differ or be negative.',
      estDiff: 'Estimated difference from the 0% path',
      noneApplied: 'No annual return assumption applied',
    },
    compare: {
      heading: 'Current path and the plan you\u2019re exploring',
      current: 'Current path',
      plan: 'Plan you\u2019re exploring',
      contribution: 'Monthly contribution',
      monthlyDiff: 'Monthly difference',
      projected: 'Projected at the goal',
      remainingGap: 'Remaining to target',
      aboveTarget: 'Above target',
      exactly: 'Exactly at target',
      progress: 'Projected progress',
      changed: 'changed',
      unchanged: 'unchanged',
    },
    progressExplain: 'This percentage compares the projected amount with the goal you entered. It is not a score or a judgment about the goal.',
    alreadyCovered: 'The amount you\u2019ve set aside already covers the goal you entered. You can still explore a monthly contribution, including zero.',
    states: {
      beyondLimit: 'These numbers grow larger than this tool can safely display, so a projection isn\u2019t shown. You can try smaller values.',
    },
    keep: 'Keep this as my plan',
    reset: 'Reset',
    leave: 'Leave without saving',
    cantAdopt: 'Fill in a valid goal and amounts to keep this as your plan.',
    errors: {
      blank: 'Enter an amount.',
      negative: 'Enter zero or more.',
      nonNumeric: 'Enter a number.',
      decimalsUsd: 'Use at most two decimal places.',
      wholeKrw: 'Enter a whole amount, with no decimals.',
      tooLarge: 'That\u2019s larger than this tool can handle. Try a smaller number.',
      targetZero: 'Enter a target above zero.',
      monthsWhole: 'Enter a whole number of months.',
      monthsRange: `Enter between 1 and ${600} months.`,
      nameBlank: 'Name this goal.',
      nameLong: 'Use a shorter name.',
      syntax: 'Use an ordinary number without commas or scientific notation.',
      returnRange: 'Use an ordinary percentage between -50 and 50, with up to two decimal places.',
    },
    confirm: {
      heading: 'Keep this plan?',
      goal: 'Goal',
      yourChoice: 'This is the plan you chose, not a FinE Companion recommendation.',
      returnChoice: 'This adjusted amount uses an annual assumption you chose to explore \u2014 not a recommendation or forecast, and not more accurate than the simple estimate.',
      confirm: 'Yes, keep it',
      cancel: 'Not yet',
      adopted: 'Saved to your plans. You can review, edit, or remove it any time.',
    },
    replace: { heading: 'Replace your current goal plan?', body: 'You already have a saved goal plan. Keeping this one will replace it.', confirm: 'Replace it', cancel: 'Keep the old one' },
    review: { heading: 'Your saved goal plan', note: 'This is the plan you kept. Nothing here changes it.', edit: 'Edit this plan', backToPlans: 'Back to My plans', close: 'Close' },
    edit: { heading: 'Editing your goal plan', note: 'Your saved plan stays as it is until you keep a new one.' },
    noChangeNote: 'Current and planned contributions are the same \u2014 you can still keep this as your goal plan.',
  },
  ko: {
    label: '목표 계획',
    purpose: '매달 일정 금액을 계속 모으면 목표 시점에 어디쯤 있을 수 있는지 살펴보세요. 이건 내 계획을 살펴보기 위한 것이지 목표를 정해주거나 추천하거나 평가하는 게 아니에요.',
    currencyChoice: { label: '이 계획의 통화', usd: '미국 달러 ($)', krw: '한국 원 (\u20a9)' },
    type: {
      heading: '어떤 목표인가요?',
      education: '교육',
      custom: '다른 목표',
      nameLabel: '이 목표의 이름',
      namePlaceholder: '예: 새 차, 집 계약금',
      educationName: '교육',
    },
    fields: {
      target: '목표금액',
      setAside: '이미 모아둔 금액',
      months: '목표까지 남은 개월',
      currentContribution: '현재 매달 넣는 금액',
      plannedContribution: '살펴볼 매달 넣는 금액',
    },
    fieldHelp: {
      target: '이루려는 미래 금액이에요.',
      setAside: '지금까지 이 목표를 위해 모은 금액이에요.',
      months: '지금부터의 개월 수(정수)예요.',
      currentContribution: '지금 이 목표에 매달 넣는 금액이에요.',
      plannedContribution: '시도해보고 싶은 매달 금액이에요.',
    },
    assumptionsHeading: '이 추정이 가정하는 것',
    assumptions: [
      '투자 수익 없음',
      '이자 없음',
      '물가 상승 반영 없음',
      '세금·수수료 없음',
      '중도 인출 없음',
      '매달 한 번 납입',
      '목표금액은 당신이 고른 미래 금액',
      '실제 삶과 비용은 달라질 수 있음',
    ],
    assumptionsActive: [
      '당신이 입력한 일정한 연간 수익률 또는 이자율 가정',
      '연간 이율을 그에 상응하는 월 이율로 환산해요',
      '월말 납입 전에 수익을 먼저 반영해요',
      '실제 수익률은 달라질 수 있고 음수가 될 수도 있어요',
      '물가 상승 반영 없음',
      '세금·수수료 없음',
      '중도 인출 없음',
      '매달 한 번 납입',
      '목표금액은 당신이 고른 미래 금액',
      '실제 삶과 비용은 달라질 수 있음',
    ],
    optional: {
      heading: '선택 가정으로 결과 조정하기',
      help: '살펴보고 싶은 가정만 추가해 보세요. 아무것도 바꾸지 않고 지금의 단순한 추정치를 그대로 사용할 수도 있어요.',
      optIn: '연간 수익률 또는 이자율 가정 반영하기',
      field: '연간 수익률 또는 이자율 가정',
      fieldHelp: '직접 살펴보기 위해 고르는 값이며, 예상 수익률이나 권장 수익률이 아니에요.',
      applied: '반영한 연간 수익률 또는 이자율 가정',
      uncertainty: '조정된 금액은 여기 입력한 연간 가정을 바탕으로 한 추정치예요. 미래를 예측하거나 보장하는 결과가 아니며 실제 수익률은 달라지거나 음수가 될 수도 있어요.',
      estDiff: '0% 경로와 비교한 추정 차이',
      noneApplied: '연간 수익률 가정을 반영하지 않았어요',
    },
    compare: {
      heading: '현재 경로와 살펴보는 계획',
      current: '현재 경로',
      plan: '살펴보는 계획',
      contribution: '매달 넣는 금액',
      monthlyDiff: '월 차이',
      projected: '목표 시점 예상액',
      remainingGap: '목표까지 남은 금액',
      aboveTarget: '목표 초과액',
      exactly: '목표와 같음',
      progress: '예상 진행률',
      changed: '바뀜',
      unchanged: '그대로',
    },
    progressExplain: '이 비율은 예상 준비금액을 입력한 목표금액과 비교한 값이에요. 목표에 대한 점수나 평가가 아니에요.',
    alreadyCovered: '이미 모아둔 금액이 입력한 목표를 이미 채워요. 매달 넣는 금액은 0을 포함해 계속 살펴볼 수 있어요.',
    states: {
      beyondLimit: '숫자가 이 도구가 안전하게 표시할 수 있는 범위보다 커져, 예상액을 보여줄 수 없어요. 더 작은 값을 시도해 보세요.',
    },
    keep: '이걸 내 계획으로 저장',
    reset: '되돌리기',
    leave: '저장하지 않고 나가기',
    cantAdopt: '저장하려면 유효한 목표와 금액을 입력해 주세요.',
    errors: {
      blank: '금액을 넣어 주세요.',
      negative: '0 이상 넣어 주세요.',
      nonNumeric: '숫자를 넣어 주세요.',
      decimalsUsd: '소수점은 두 자리까지만 넣어 주세요.',
      wholeKrw: '소수점 없이 정수 금액을 넣어 주세요.',
      tooLarge: '이 도구가 다룰 수 있는 값보다 커요. 더 작은 숫자를 넣어 주세요.',
      targetZero: '0보다 큰 목표금액을 넣어 주세요.',
      monthsWhole: '개월 수를 정수로 넣어 주세요.',
      monthsRange: '1개월에서 600개월 사이로 넣어 주세요.',
      nameBlank: '이 목표의 이름을 넣어 주세요.',
      nameLong: '더 짧은 이름을 넣어 주세요.',
      syntax: '쉼표나 지수표기 없이 일반 숫자로 입력해 주세요.',
      returnRange: '-50에서 50 사이의 일반 백분율을 소수점 둘째 자리까지 입력해 주세요.',
    },
    confirm: {
      heading: '이 계획을 저장할까요?',
      goal: '목표',
      yourChoice: '이건 당신이 고른 계획이에요. FinE Companion의 추천이 아니에요.',
      returnChoice: '이 조정 금액은 당신이 살펴보려고 고른 연간 가정을 사용한 값이에요 \u2014 추천이나 예측이 아니고, 단순한 추정치보다 더 정확한 것도 아니에요.',
      confirm: '네, 저장할게요',
      cancel: '아직요',
      adopted: '내 계획에 저장됐어요. 언제든 다시 보거나, 수정하거나, 삭제할 수 있어요.',
    },
    replace: { heading: '지금 목표 계획을 바꿀까요?', body: '이미 저장된 목표 계획이 있어요. 이걸 저장하면 그 계획을 대신해요.', confirm: '바꿀게요', cancel: '기존 것 유지' },
    review: { heading: '저장된 목표 계획', note: '당신이 저장한 계획이에요. 여기서는 아무것도 바뀌지 않아요.', edit: '이 계획 수정', backToPlans: '내 계획으로 돌아가기', close: '닫기' },
    edit: { heading: '목표 계획 수정 중', note: '새로 저장하기 전까지 기존 계획은 그대로예요.' },
    noChangeNote: '현재와 계획한 매달 금액이 같아요 \u2014 그래도 이걸 목표 계획으로 저장할 수 있어요.',
  },
}
