// Insurance Protection Planning Tool — copy. EN/KO parity. Strictly non-
// prescriptive: never tells the person how much they need, never recommends a
// policy/carrier/type, never calls a gap dangerous or classifies under/over-
// insured. The tool only compares entered responsibilities with entered resources.
export const insuranceContent = {
  en: {
    label: 'Protection planning',
    purpose: 'A bounded scenario: compare the responsibilities you want this plan to hold up against the protection resources you have or want to explore. It is not a full insurance-needs analysis, and it does not tell you how much coverage to get, recommend a policy, or quote a premium.',
    currencyChoice: { label: 'Currency for this plan', usd: 'US dollars ($)', krw: 'Korean won (\u20a9)' },
    responsibilitiesHeading: 'Responsibilities you\u2019re entering',
    assumptionsHeading: 'Assumptions used in this comparison',
    currentHeading: 'Protection resources you have',
    choosingHeading: 'Coverage you\u2019re exploring',
    fields: {
      monthlySupport: 'Monthly household support to protect',
      years: 'Years of support',
      oneTime: 'One-time responsibilities',
      currentCoverage: 'Current dedicated insurance coverage',
      otherResources: 'Other resources to count',
      exploredCoverage: 'Insurance coverage amount to explore',
    },
    fieldHelp: {
      monthlySupport: 'A monthly amount you\u2019d want this plan to help carry.',
      years: 'A whole number of years to extend that monthly support.',
      oneTime: 'Obligations or goals you want included once (enter 0 if none).',
      currentCoverage: 'Insurance you already have dedicated to this purpose.',
      otherResources: 'Any other resources you want to count here.',
      exploredCoverage: 'A coverage amount you\u2019d like to try. This isn\u2019t a recommendation.',
    },
    meaning: 'The responsibilities entered describe what you want this plan to hold up. The protection resources entered show one possible way those responsibilities might be supported. The comparison does not decide the right amount for you.',
    assumptions: [
      'this tool uses only the responsibilities and resources entered here',
      'monthly household support is extended across the number of years entered',
      'one-time responsibilities are added once',
      'current resources include only the coverage and other resources entered',
      'the explored path changes only the insurance coverage amount',
      'no inflation, investment growth, tax, policy exclusions, benefit timing, or legal rules are modeled',
      'actual insurance benefits depend on policy terms and claims eligibility',
      'the result is not a recommendation or policy quote',
    ],
    compare: {
      heading: 'What you have now and what you\u2019re exploring',
      responsibilities: 'Responsibilities entered',
      current: 'Protection you have now',
      explored: 'Protection you\u2019re exploring',
      monthlySupport: 'Monthly support',
      years: 'Years',
      oneTime: 'One-time',
      totalResp: 'Total responsibilities',
      coverage: 'Insurance coverage',
      other: 'Other resources',
      totalRes: 'Total protection resources',
      coverageDiff: 'Insurance coverage difference',
      uncoveredChangeDown: 'Amount not covered decreases by',
      uncoveredChangeUp: 'Amount not covered increases by',
      uncoveredChangeSame: 'Amount not covered is unchanged',
      shareChange: 'Change in share',
      changed: 'changed',
      unchanged: 'unchanged',
      sharedNote: 'Other resources stay the same in both paths; the explored path changes only the insurance coverage.',
      notDecide: 'This tool does not determine the correct coverage for you.',
    },
    amount: {
      uncovered: 'Amount not covered by the resources entered',
      none: 'No difference under these entries',
      beyond: 'Amount beyond the responsibilities entered',
    },
    share: {
      heading: 'Share of the responsibilities entered',
      current: 'Now',
      explored: 'Exploring',
      change: 'Change',
      note: 'This percentage compares the protection resources entered with the responsibilities entered. It is not a score, recommendation, or coverage standard.',
      needResp: 'A comparison percentage needs an entered responsibility amount above zero.',
    },
    reflection: 'A quiet question, not a push: which responsibilities matter most in this picture, and how does the coverage you\u2019re exploring sit alongside the rest of your financial life?',
    keep: 'Keep this as my plan',
    reset: 'Reset',
    leave: 'Leave without saving',
    cantAdopt: 'Fill in valid values to keep this as your plan.',
    noResp: 'Add at least one responsibility to compare with the protection resources entered.',
    errors: {
      blank: 'Enter a value.',
      negative: 'Enter zero or more.',
      syntax: 'Use ordinary numbers without commas or scientific notation.',
      decimalsUsd: 'Use at most two decimal places.',
      wholeKrw: 'Enter a whole amount, with no decimals.',
      tooLarge: 'That\u2019s larger than this tool can handle. Try a smaller number.',
      yearsWhole: 'Enter a whole number of years.',
      yearsRange: `Enter between 1 and ${60} years.`,
    },
    states: {
      beyondLimit: 'These numbers grow larger than this tool can safely display, so no comparison is shown. You can try smaller values.',
    },
    confirm: {
      heading: 'Keep this plan?',
      yourChoice: 'This is the scenario you chose from the values you entered \u2014 not a FinE Companion recommendation or policy quote.',
      confirm: 'Yes, keep it',
      cancel: 'Not yet',
      adopted: 'Saved to your plans. You can review, edit, or remove it any time.',
    },
    replace: { heading: 'Replace your current protection plan?', body: 'You already have a saved protection plan. Keeping this one will replace it.', confirm: 'Replace it', cancel: 'Keep the old one' },
    identicalNote: 'Your saved plan already matches these values. Change at least one to keep a new version.',
    review: { heading: 'Your saved protection plan', note: 'This is the scenario you kept, from the values you entered. Nothing here changes it.', edit: 'Edit this plan', backToPlans: 'Back to My plans', close: 'Close' },
    edit: { heading: 'Editing your protection plan', note: 'Your saved plan stays as it is until you keep a new one.' },
  },
  ko: {
    label: '보호 계획',
    purpose: '한정된 시나리오예요. 이 계획으로 지키고 싶은 책임과, 지금 가진 또는 살펴보려는 보호자원을 비교해요. 종합 보험 필요분석이 아니며, 얼마를 가입해야 하는지 알려주거나 상품을 추천하거나 보험료를 산출하지 않아요.',
    currencyChoice: { label: '이 계획의 통화', usd: '미국 달러 ($)', krw: '한국 원 (\u20a9)' },
    responsibilitiesHeading: '입력하는 책임',
    assumptionsHeading: '이 비교에서 사용한 가정',
    currentHeading: '지금 가진 보호자원',
    choosingHeading: '살펴보는 보장금액',
    fields: {
      monthlySupport: '지키려는 월 가계 지원액',
      years: '지원 연수',
      oneTime: '일시 책임금액',
      currentCoverage: '현재 전용 보험 보장액',
      otherResources: '함께 셀 다른 자원',
      exploredCoverage: '살펴볼 보험 보장금액',
    },
    fieldHelp: {
      monthlySupport: '이 계획이 매달 함께 감당하길 바라는 금액이에요.',
      years: '그 월 지원을 이어갈 연수(정수)예요.',
      oneTime: '한 번 포함하고 싶은 의무나 목표예요 (없으면 0).',
      currentCoverage: '이 목적에 이미 배정한 보험이에요.',
      otherResources: '여기서 함께 세고 싶은 다른 자원이에요.',
      exploredCoverage: '시도해보고 싶은 보장금액이에요. 추천이 아니에요.',
    },
    meaning: '입력한 책임은 이 계획으로 지키고 싶은 부분을 보여줘요. 입력한 보호자원은 그 책임을 뒷받침할 수 있는 한 가지 모습을 보여줘요. 이 비교가 당신에게 맞는 금액을 대신 정해주지는 않아요.',
    assumptions: [
      '이 도구는 여기 입력한 책임과 자원만 사용해요',
      '월 가계 지원액은 입력한 연수만큼 이어져요',
      '일시 책임금액은 한 번 더해져요',
      '현재 자원은 입력한 보장액과 다른 자원만 포함해요',
      '살펴보는 경로는 보험 보장금액만 바꿔요',
      '물가, 투자 성장, 세금, 약관 면책, 지급 시점, 법적 규칙은 반영하지 않아요',
      '실제 보험금은 약관과 청구 자격에 따라 달라져요',
      '결과는 추천이나 보험 견적이 아니에요',
    ],
    compare: {
      heading: '지금 가진 것과 살펴보는 것',
      responsibilities: '입력한 책임',
      current: '지금 가진 보호',
      explored: '살펴보는 보호',
      monthlySupport: '월 지원액',
      years: '연수',
      oneTime: '일시 금액',
      totalResp: '총 책임금액',
      coverage: '보험 보장액',
      other: '다른 자원',
      totalRes: '총 보호자원',
      coverageDiff: '보험 보장액 차이',
      uncoveredChangeDown: '채워지지 않는 금액이 줄어드는 정도',
      uncoveredChangeUp: '채워지지 않는 금액이 늘어나는 정도',
      uncoveredChangeSame: '채워지지 않는 금액은 그대로예요',
      shareChange: '비중 변화',
      changed: '바뀜',
      unchanged: '그대로',
      sharedNote: '다른 자원은 두 경로에서 같아요. 살펴보는 경로는 보험 보장액만 바꿔요.',
      notDecide: '이 도구는 당신에게 맞는 보장금액을 대신 정하지 않아요.',
    },
    amount: {
      uncovered: '입력한 보호자원으로 채워지지 않는 금액',
      none: '입력한 값에서는 차이가 없어요',
      beyond: '입력한 책임금액을 넘어서는 금액',
    },
    share: {
      heading: '입력한 책임금액 대비 보호 비중',
      current: '지금',
      explored: '살펴봄',
      change: '변화',
      note: '이 비율은 입력한 보호자원을 입력한 책임금액과 비교한 값이에요. 점수나 권장 보장기준이 아니에요.',
      needResp: '비교 비율을 보려면 입력한 책임금액이 0보다 커야 해요.',
    },
    reflection: '몰아붙이는 게 아니라 잠시 떠올려보는 질문이에요. 이 그림에서 가장 지키고 싶은 책임은 무엇인가요? 그리고 살펴본 보장금액은 지금의 다른 재무생활과 어떻게 어울리나요?',
    keep: '이걸 내 계획으로 저장',
    reset: '되돌리기',
    leave: '저장하지 않고 나가기',
    cantAdopt: '저장하려면 유효한 값을 입력해 주세요.',
    noResp: '입력한 보호자원과 비교하려면 보호하려는 책임을 하나 이상 입력해 주세요.',
    errors: {
      blank: '값을 넣어 주세요.',
      negative: '0 이상 넣어 주세요.',
      syntax: '쉼표나 지수표기 없이 일반 숫자로 입력해 주세요.',
      decimalsUsd: '소수점은 두 자리까지만 넣어 주세요.',
      wholeKrw: '소수점 없이 정수 금액을 넣어 주세요.',
      tooLarge: '이 도구가 다룰 수 있는 값보다 커요. 더 작은 숫자를 넣어 주세요.',
      yearsWhole: '연수를 정수로 넣어 주세요.',
      yearsRange: '1년에서 60년 사이로 넣어 주세요.',
    },
    states: {
      beyondLimit: '숫자가 이 도구가 안전하게 표시할 수 있는 범위보다 커져, 비교를 보여줄 수 없어요. 더 작은 값을 시도해 보세요.',
    },
    confirm: {
      heading: '이 계획을 저장할까요?',
      yourChoice: '이건 당신이 입력한 값에서 고른 시나리오예요 \u2014 FinE Companion의 추천이나 보험 견적이 아니에요.',
      confirm: '네, 저장할게요',
      cancel: '아직요',
      adopted: '내 계획에 저장됐어요. 언제든 다시 보거나, 수정하거나, 삭제할 수 있어요.',
    },
    replace: { heading: '지금 보호 계획을 바꿀까요?', body: '이미 저장된 보호 계획이 있어요. 이걸 저장하면 그 계획을 대신해요.', confirm: '바꿀게요', cancel: '기존 것 유지' },
    identicalNote: '저장된 계획이 이미 이 값에 정확히 일치해요. 새로 저장하려면 최소 한 가지를 바꿔 주세요.',
    review: { heading: '저장된 보호 계획', note: '당신이 입력한 값에서 저장한 시나리오예요. 여기서는 아무것도 바뀌지 않아요.', edit: '이 계획 수정', backToPlans: '내 계획으로 돌아가기', close: '닫기' },
    edit: { heading: '보호 계획 수정 중', note: '새로 저장하기 전까지 기존 계획은 그대로예요.' },
  },
}
