// Cash Flow Planning Tool — copy. English/Korean parity.
// RC5.0: multi-field scenarios + planning-only baseline entry.
export const planContent = {
  en: {
    label: 'Explore your cash flow',
    purpose: 'See what changes if you adjust your monthly money. Change one part or several — it\u2019s yours to try.',
    leverLabels: {
      income: 'Money coming in',
      essentials: 'Must-pays',
      nonEssentials: 'Flexible spending',
      debt: 'Debt payment',
    },
    fieldHelp: {
      income: 'What comes in each month',
      essentials: 'Rent, bills, groceries — the must-pays',
      nonEssentials: 'Flexible, nice-to-have spending',
      debt: 'Card and loan payments',
    },
    baseline: {
      heading: 'Your current monthly money',
      help: 'Rough monthly amounts are fine. These are used only for this plan — we won\u2019t change your check-up.',
      caption: 'Values you entered for this plan',
      continue: 'Continue',
      edit: 'Edit these values',
    },
    currencyChoice: {
      label: 'Currency for this plan',
      usd: 'US dollars ($)',
      krw: 'Korean won (₩)',
    },
    current: {
      caption: 'From your check-up',
      roomLabel: 'Room left now',
      gapLabel: 'Short now',
      outLabel: 'Going out now',
    },
    explore: {
      heading: 'Your plan',
      help: 'Change any of these amounts. Leave the rest as they are.',
      now: 'Now',
      changed: 'Changed',
    },
    compare: {
      heading: 'What changes',
      roomBefore: 'Room now',
      roomAfter: 'Room in this plan',
      gapBefore: 'Short now',
      gapAfter: 'Short in this plan',
      outAfter: 'Going out in this plan',
      total: 'Total change',
      noneYet: 'Nothing has changed yet. Adjust an amount above to see what happens.',
    },
    ratio: {
      viewLabel: 'View comparison as',
      amounts: 'Amounts',
      ratios: 'Ratios',
      mustPay: 'Must-pay share',
      flexible: 'Flexible-spending share',
      roomShare: 'Monthly room share',
      gapShare: 'Monthly gap share',
      now: 'Now',
      inPlan: 'In this plan',
      change: 'Change',
      points: 'percentage points',
      noChange: 'No change in this share.',
      explanation: 'These percentages show how this month is arranged. They are not a score or a target.',
      incomeZero: 'Ratios need income above zero. You can still explore this plan in amounts.',
      backToAmounts: 'Back to Amounts',
    },
    source: {
      checkup: 'Started from your check-up',
      planning: 'Started from values you entered',
    },
    reset: 'Reset',
    leave: 'Leave without saving',
    keep: 'Keep this as my plan',
    noChange: 'There\u2019s no change to carry forward yet. Adjust an amount, or leave without keeping anything.',
    unavailableLine: 'We don\u2019t have your full cash flow picture yet — you can enter your own values to make a plan.',
    unavailableLink: 'Complete your check-up',
    errors: {
      blank: 'Enter an amount to see what changes.',
      negative: 'Please enter an amount of zero or more.',
      nonNumeric: 'Please enter a number.',
      fractional: 'Please enter a whole amount, with no decimals.',
      tooLarge: 'That amount is larger than this tool can show. Try a smaller number.',
    },
    overflow: 'This plan is larger than the tool can safely display. Try smaller amounts.',
    uncertainty:
      'This is based on the monthly amounts here, with your changes applied. Real months vary — it\u2019s a way to explore, not a forecast or a promise.',
    reflection: 'Does that tradeoff feel worth it to you? That part is yours to decide.',
    confirm: {
      heading: 'Keep this plan?',
      listIntro: 'You\u2019re choosing to keep these changes:',
      changeLine: (label, before, after) => `${label}: ${before} \u2192 ${after}`,
      roomLine: (room) => `Room left this month: ${room}`,
      gapLine: (gap) => `Short this month: ${gap}`,
      yourChoice: 'This is the plan you chose, not a FinE Companion recommendation.',
      confirm: 'Yes, keep it',
      cancel: 'Not yet',
      adopted: 'Saved to your plans. You can review, edit, or remove it any time.',
    },
    replace: {
      heading: 'Replace your current plan?',
      body: 'You already have a saved cash flow plan. Keeping this one will replace it.',
      confirm: 'Replace it',
      cancel: 'Keep the old one',
    },
    review: {
      heading: 'Your saved plan',
      note: 'This is the plan you kept. Nothing here changes it.',
      staleNote: 'This is based on an earlier check-up.',
      checkupPath: 'Go to your check-up',
      edit: 'Edit this plan',
      close: 'Close',
      backToPlans: 'Back to My plans',
    },
    edit: {
      heading: 'Editing your plan',
      note: 'Your saved plan stays as it is until you keep a new one.',
      staleNote: 'Your check-up has changed since you saved this. Editing starts from your current picture.',
    },
  },
  ko: {
    label: '내 현금 흐름 살펴보기',
    purpose: '매달의 돈을 바꿔 보면 무엇이 달라지는지 살펴보세요. 한 가지만, 또는 여러 가지를 바꿔 봐도 좋아요.',
    leverLabels: {
      income: '들어오는 돈',
      essentials: '꼭 나가는 돈',
      nonEssentials: '융통 가능한 지출',
      debt: '부채 상환',
    },
    fieldHelp: {
      income: '매달 들어오는 돈',
      essentials: '월세, 공과금, 식비 — 꼭 나가는 돈',
      nonEssentials: '융통 가능한, 있으면 좋은 지출',
      debt: '카드와 대출 상환액',
    },
    baseline: {
      heading: '현재 매달의 돈',
      help: '대략적인 월 금액이면 충분해요. 이 값들은 이 계획에만 쓰이고, 체크업은 바뀌지 않아요.',
      caption: '이 계획을 위해 입력한 값',
      continue: '계속하기',
      edit: '이 값 수정하기',
    },
    currencyChoice: {
      label: '이 계획의 통화',
      usd: '미국 달러 ($)',
      krw: '한국 원 (₩)',
    },
    current: {
      caption: '체크업에서 가져온 값',
      roomLabel: '지금 남는 여유',
      gapLabel: '지금 부족액',
      outLabel: '지금 나가는 돈',
    },
    explore: {
      heading: '내 계획',
      help: '아래 금액 중 무엇이든 바꿔 보세요. 나머지는 그대로 두면 돼요.',
      now: '현재',
      changed: '변경됨',
    },
    compare: {
      heading: '무엇이 달라지나요',
      roomBefore: '현재 여유',
      roomAfter: '이 계획의 여유',
      gapBefore: '현재 부족액',
      gapAfter: '이 계획의 부족액',
      outAfter: '이 계획에서 나가는 돈',
      total: '전체 변화',
      noneYet: '아직 달라진 게 없어요. 위에서 금액을 바꿔 무엇이 달라지는지 살펴보세요.',
    },
    ratio: {
      viewLabel: '비교 보기 방식',
      amounts: '금액으로 보기',
      ratios: '비율로 보기',
      mustPay: '꼭 나가는 돈의 비중',
      flexible: '유연한 지출의 비중',
      roomShare: '월간 여유 비중',
      gapShare: '월간 부족분 비중',
      now: '현재',
      inPlan: '이 계획',
      change: '변화',
      points: '%p',
      noChange: '이 비중은 달라지지 않았어요.',
      explanation: '이 비율은 이번 달의 돈 배치를 보여줘요. 점수나 목표 기준은 아니에요.',
      incomeZero: '비율을 보려면 수입이 0보다 커야 해요. 금액으로는 이 계획을 계속 살펴볼 수 있어요.',
      backToAmounts: '금액으로 보기',
    },
    source: {
      checkup: '체크업에서 시작함',
      planning: '입력한 값에서 시작함',
    },
    reset: '되돌리기',
    leave: '저장하지 않고 나가기',
    keep: '이걸 내 계획으로 저장',
    noChange: '아직 저장할 변화가 없어요. 금액을 바꾸거나, 아무것도 저장하지 않고 나가도 돼요.',
    unavailableLine: '아직 현금 흐름 정보가 다 없어요 — 직접 값을 입력해 계획을 만들 수 있어요.',
    unavailableLink: '체크업 완성하기',
    errors: {
      blank: '달라지는 걸 보려면 금액을 넣어 주세요.',
      negative: '0 이상 금액을 넣어 주세요.',
      nonNumeric: '숫자를 넣어 주세요.',
      fractional: '소수점 없이 정수 금액을 넣어 주세요.',
      tooLarge: '이 도구가 표시할 수 있는 금액보다 커요. 더 작은 숫자를 넣어 주세요.',
    },
    overflow: '이 계획은 도구가 안전하게 표시할 수 있는 범위보다 커요. 더 작은 금액을 넣어 보세요.',
    uncertainty:
      '이건 여기 있는 월 금액에 당신의 변화를 적용한 결과예요. 실제 달마다 다를 수 있고, 예측이나 약속이 아니라 살펴보기 위한 거예요.',
    reflection: '그 맞바꿈이 당신에게 가치 있게 느껴지나요? 그건 당신이 정할 몫이에요.',
    confirm: {
      heading: '이 계획을 저장할까요?',
      listIntro: '저장할 변화는 다음과 같아요:',
      changeLine: (label, before, after) => `${label}: ${before} \u2192 ${after}`,
      roomLine: (room) => `이번 달 남는 여유: ${room}`,
      gapLine: (gap) => `이번 달 부족액: ${gap}`,
      yourChoice: '이건 당신이 고른 계획이에요. FinE Companion의 추천이 아니에요.',
      confirm: '네, 저장할게요',
      cancel: '아직요',
      adopted: '내 계획에 저장됐어요. 언제든 다시 보거나, 수정하거나, 삭제할 수 있어요.',
    },
    replace: {
      heading: '지금 계획을 바꿀까요?',
      body: '이미 저장된 현금 흐름 계획이 있어요. 이걸 저장하면 그 계획을 대신해요.',
      confirm: '바꿀게요',
      cancel: '기존 것 유지',
    },
    review: {
      heading: '저장된 계획',
      note: '당신이 저장한 계획이에요. 여기서는 아무것도 바뀌지 않아요.',
      staleNote: '이건 이전 체크업을 바탕으로 한 계획이에요.',
      checkupPath: '체크업으로 가기',
      edit: '이 계획 수정',
      close: '닫기',
      backToPlans: '내 계획으로 돌아가기',
    },
    edit: {
      heading: '계획 수정 중',
      note: '새로 저장하기 전까지 기존 계획은 그대로예요.',
      staleNote: '저장한 뒤로 체크업이 바뀌었어요. 수정은 지금 정보에서 시작해요.',
    },
  },
}
