// Retirement Planning Tool — copy. EN/KO parity. Non-forecast, non-recommendation:
// the annual return is a visible ASSUMPTION, never a promise or an expected value.
export const retirementContent = {
  en: {
    label: 'Retirement planning',
    purpose: 'If you continue with this monthly contribution, see what it might become by the retirement point you enter. Every assumption is shown, and you can explore a different monthly contribution. This is not a forecast, a promise, or a recommendation.',
    currencyChoice: { label: 'Currency for this plan', usd: 'US dollars ($)', krw: 'Korean won (\u20a9)' },
    choosingHeading: 'What you\u2019re choosing',
    currentPathHeading: 'Your current path',
    assumesHeading: 'What this estimate assumes',
    fields: {
      currentBalance: 'Current retirement balance',
      years: 'Years until retirement',
      currentContribution: 'Current monthly contribution',
      plannedContribution: 'Monthly contribution to explore',
      annualReturn: 'Assumed annual return',
    },
    fieldHelp: {
      currentBalance: 'What you\u2019ve saved for retirement so far.',
      years: 'A whole number of years from now.',
      currentContribution: 'What you contribute each month now.',
      plannedContribution: 'A monthly amount you\u2019d like to try.',
      annualReturn: 'An assumption you choose \u2014 not a likely or guaranteed rate. Between \u221250 and 50.',
    },
    returnNote: 'The annual return is an assumption you enter, not a recommendation or a rate we expect. Both paths use the same balance, time horizon, and return assumption.',
    assumptions: [
      'one retirement balance',
      'one contribution each month',
      'the contribution is added at the end of each month',
      'a constant annual return assumption',
      'the annual return is converted to an equivalent monthly rate',
      'no employer match',
      'no fees',
      'no taxes',
      'no inflation adjustment',
      'no withdrawals',
      'no contribution increases',
      'no pension or Social Security',
      'actual investment returns vary and may be negative',
    ],
    optional: {
      heading: 'Adjust with optional assumptions',
      help: 'Add only the assumptions you want to explore. You can keep the current estimate without changing anything here.',
      employerOptIn: 'Include an employer monthly contribution',
      employerField: 'Employer monthly contribution',
      employerHelp: 'Enter a monthly amount only when you want to include it in this estimate. This tool does not interpret an employer matching formula.',
      changeOptIn: 'Include an annual change in my monthly contribution',
      changeField: 'Annual change in monthly contribution',
      changeHelp: 'This changes your personal monthly contribution once after each completed 12-month period. It does not change the employer amount.',
      inflationOptIn: 'Show an estimate in today\u2019s purchasing power',
      inflationField: 'Annual inflation assumption',
      inflationHelp: 'This does not change the projected retirement balance. It adds a second view of what that future amount may represent in today\u2019s purchasing power.',
      appliedEmployer: 'Employer monthly contribution',
      appliedChange: 'Annual contribution change',
      appliedInflation: 'Inflation assumption',
      finalPersonal: 'Final monthly contribution',
      totalPersonal: 'Total personal contributions',
      totalEmployer: 'Total employer contributions',
      basicDiff: 'Estimated difference from the basic path',
      ppLabel: 'Estimated in today\u2019s purchasing power',
      ppNominal: 'Projected balance (nominal)',
      ppExplain: 'This is a second view of the projected balance using the inflation assumption entered here. It does not change the future nominal balance and is not a forecast of future prices.',
      homeInToday: 'In today\u2019s purchasing power',
    },
    assumeReplace: {
      noEmployer: 'no employer match',
      employer: 'a fixed employer monthly contribution you entered is added each month (no matching formula or vesting is modeled)',
      noIncrease: 'no contribution increases',
      change: 'your personal contribution changes once after each completed 12-month period by the rate you entered',
      noInflation: 'no inflation adjustment',
      inflation: 'inflation is used only for a separate purchasing-power view; nominal balances are unchanged',
    },
    compare: {
      heading: 'Current path and the plan you\u2019re exploring',
      current: 'Current path',
      plan: 'Plan you\u2019re exploring',
      balance: 'Current balance',
      years: 'Years until retirement',
      annualReturn: 'Assumed annual return',
      contribution: 'Monthly contribution',
      monthlyDiff: 'Monthly difference',
      projected: 'Projected balance',
      totalContrib: 'Total future contributions',
      growth: 'Estimated growth',
      balanceDiff: 'Projected-balance difference',
      changed: 'changed',
      unchanged: 'unchanged',
      sharedNote: 'Balance, time horizon, and return assumption are shared by both paths.',
    },
    uncertainty: 'This is an estimate under the time, contribution, and return assumptions entered here. It is not a forecast or a promise, and actual returns will vary.',
    ratio: {
      heading: 'Contribution share of monthly income',
      current: 'Current',
      plan: 'Planned',
      change: 'Change',
      note: 'A plain share of the monthly income from your check-up \u2014 not a recommended rate or a benchmark.',
    },
    reflection: 'A quiet question, not a push: what would this monthly contribution ask of the life you\u2019re living now, and how does the longer-term possibility sit alongside the room you need today?',
    keep: 'Keep this as my plan',
    reset: 'Reset',
    leave: 'Leave without saving',
    cantAdopt: 'Fill in valid values and assumptions to keep this as your plan.',
    errors: {
      blank: 'Enter a value.',
      negative: 'Enter zero or more.',
      nonNumeric: 'Enter a number.',
      decimalsUsd: 'Use at most two decimal places.',
      wholeKrw: 'Enter a whole amount, with no decimals.',
      tooLarge: 'That\u2019s larger than this tool can handle. Try a smaller number.',
      yearsWhole: 'Enter a whole number of years.',
      yearsRange: `Enter between 1 and ${60} years.`,
      returnRange: 'Enter an annual return between \u221250 and 50.',
      returnNonNumeric: 'Enter the annual return as a number.',
      syntax: 'Use an ordinary number without commas or scientific notation.',
      pctRange: 'Use an ordinary percentage between -50 and 50, with up to two decimal places.',
    },
    states: {
      beyondLimit: 'These numbers grow larger than this tool can safely display, so no projection is shown. You can try smaller values or a lower return assumption.',
    },
    confirm: {
      heading: 'Keep this plan?',
      yourChoice: 'This is the plan you chose under the assumptions you entered \u2014 not a FinE Companion recommendation or forecast.',
      confirm: 'Yes, keep it',
      cancel: 'Not yet',
      adopted: 'Saved to your plans. You can review, edit, or remove it any time.',
    },
    replace: { heading: 'Replace your current retirement plan?', body: 'You already have a saved retirement plan. Keeping this one will replace it.', confirm: 'Replace it', cancel: 'Keep the old one' },
    review: { heading: 'Your saved retirement plan', note: 'This is the plan you kept, under the assumptions you entered. Nothing here changes it.', edit: 'Edit this plan', backToPlans: 'Back to My plans', close: 'Close' },
    edit: { heading: 'Editing your retirement plan', note: 'Your saved plan stays as it is until you keep a new one.' },
    noChangeNote: 'Current and planned contributions are the same \u2014 you can still keep this as your retirement plan.',
    identicalNote: 'Your saved plan already matches these values and assumptions. Change at least one to keep a new version.',
  },
  ko: {
    label: '은퇴 계획',
    purpose: '지금 매달 넣는 금액을 계속 이어가면, 입력한 은퇴 시점에 어느 정도가 될 수 있는지 살펴보세요. 모든 가정이 표시되고, 다른 매달 금액도 살펴볼 수 있어요. 이건 예측이나 약속, 추천이 아니에요.',
    currencyChoice: { label: '이 계획의 통화', usd: '미국 달러 ($)', krw: '한국 원 (\u20a9)' },
    choosingHeading: '당신이 고르는 것',
    currentPathHeading: '현재 경로',
    assumesHeading: '이 추정이 가정하는 것',
    fields: {
      currentBalance: '현재 은퇴 잔액',
      years: '은퇴까지 남은 연수',
      currentContribution: '현재 매달 넣는 금액',
      plannedContribution: '살펴볼 매달 넣는 금액',
      annualReturn: '가정 연간 수익률',
    },
    fieldHelp: {
      currentBalance: '지금까지 은퇴를 위해 모은 금액이에요.',
      years: '지금부터의 연수(정수)예요.',
      currentContribution: '지금 매달 넣는 금액이에요.',
      plannedContribution: '시도해보고 싶은 매달 금액이에요.',
      annualReturn: '당신이 고르는 가정이에요 \u2014 예상되거나 보장된 수익률이 아니에요. \u221250에서 50 사이.',
    },
    returnNote: '연간 수익률은 당신이 입력하는 가정이에요. 추천하거나 예상하는 수익률이 아니에요. 두 경로 모두 같은 잔액, 기간, 수익률 가정을 사용해요.',
    assumptions: [
      '하나의 은퇴 잔액',
      '매달 한 번 납입',
      '적립액은 매달 말에 더해짐',
      '일정한 연간 수익률 가정',
      '연간 수익률을 동등한 월 수익률로 환산',
      '고용주 매칭 없음',
      '수수료 없음',
      '세금 없음',
      '물가 상승 반영 없음',
      '중도 인출 없음',
      '적립액 증가 없음',
      '연금·국민연금 없음',
      '실제 투자 수익률은 달라지며 마이너스일 수 있음',
    ],
    optional: {
      heading: '선택 가정으로 결과 조정하기',
      help: '살펴보고 싶은 가정만 추가해 보세요. 아무것도 바꾸지 않고 지금의 추정치를 그대로 사용할 수도 있어요.',
      employerOptIn: '고용주 월 적립액 반영하기',
      employerField: '고용주 월 적립액',
      employerHelp: '이 추정에 포함하고 싶을 때만 월 금액을 입력하세요. 이 도구는 회사의 매칭 공식을 해석하지 않아요.',
      changeOptIn: '내 월 적립액의 연간 변화 반영하기',
      changeField: '월 적립액의 연간 변화율',
      changeHelp: '12개월이 지날 때마다 개인 월 적립액을 한 번 조정해요. 고용주 적립액은 바꾸지 않아요.',
      inflationOptIn: '오늘의 구매력으로 본 추정치 표시하기',
      inflationField: '연간 물가상승률 가정',
      inflationHelp: '은퇴 시점 예상잔액 자체를 바꾸지 않아요. 그 미래 금액을 오늘의 구매력으로 다시 본 보조 결과를 추가해요.',
      appliedEmployer: '고용주 월 적립액',
      appliedChange: '연간 적립 변화율',
      appliedInflation: '물가상승률 가정',
      finalPersonal: '최종 월 적립액',
      totalPersonal: '총 개인 적립액',
      totalEmployer: '총 고용주 적립액',
      basicDiff: '기본 경로와 비교한 추정 차이',
      ppLabel: '오늘의 구매력으로 본 추정액',
      ppNominal: '예상잔액(명목)',
      ppExplain: '입력한 물가상승률 가정으로 예상잔액을 다시 본 보조 결과예요. 미래의 명목 잔액을 바꾸지 않으며 미래 물가를 예측하는 값도 아니에요.',
      homeInToday: '오늘의 구매력으로 본 금액',
    },
    assumeReplace: {
      noEmployer: '고용주 매칭 없음',
      employer: '입력한 고정 고용주 월 적립액이 매달 더해져요 (매칭 공식이나 베스팅은 반영하지 않아요)',
      noIncrease: '적립액 증가 없음',
      change: '12개월이 지날 때마다 입력한 비율로 개인 적립액이 한 번 조정돼요',
      noInflation: '물가 상승 반영 없음',
      inflation: '물가상승률은 별도의 구매력 보기에만 사용되며 명목 잔액은 바뀌지 않아요',
    },
    compare: {
      heading: '현재 경로와 살펴보는 계획',
      current: '현재 경로',
      plan: '살펴보는 계획',
      balance: '현재 잔액',
      years: '은퇴까지 연수',
      annualReturn: '가정 연간 수익률',
      contribution: '매달 넣는 금액',
      monthlyDiff: '월 차이',
      projected: '예상 잔액',
      totalContrib: '앞으로 넣을 총액',
      growth: '추정 증가분',
      balanceDiff: '예상 잔액 차이',
      changed: '바뀜',
      unchanged: '그대로',
      sharedNote: '잔액, 기간, 수익률 가정은 두 경로가 함께 써요.',
    },
    uncertainty: '이 값은 여기 입력한 기간, 적립액, 수익률 가정을 바탕으로 한 추정치예요. 미래를 예측하거나 보장하는 값이 아니며 실제 수익률은 달라질 수 있어요.',
    ratio: {
      heading: '월 소득 대비 적립 비중',
      current: '현재',
      plan: '계획',
      change: '변화',
      note: '체크업에 입력한 월 소득 대비 단순 비중이에요 \u2014 추천 비율이나 기준이 아니에요.',
    },
    reflection: '몰아붙이는 게 아니라 잠시 떠올려보는 질문이에요. 이 매달 금액은 지금 살고 있는 삶에 무엇을 요구할까요? 그리고 더 긴 미래의 가능성은 오늘 필요한 여유와 어떻게 나란히 놓일까요?',
    keep: '이걸 내 계획으로 저장',
    reset: '되돌리기',
    leave: '저장하지 않고 나가기',
    cantAdopt: '저장하려면 유효한 값과 가정을 입력해 주세요.',
    errors: {
      blank: '값을 넣어 주세요.',
      negative: '0 이상 넣어 주세요.',
      nonNumeric: '숫자를 넣어 주세요.',
      decimalsUsd: '소수점은 두 자리까지만 넣어 주세요.',
      wholeKrw: '소수점 없이 정수 금액을 넣어 주세요.',
      tooLarge: '이 도구가 다룰 수 있는 값보다 커요. 더 작은 숫자를 넣어 주세요.',
      yearsWhole: '연수를 정수로 넣어 주세요.',
      yearsRange: '1년에서 60년 사이로 넣어 주세요.',
      returnRange: '연간 수익률을 \u221250에서 50 사이로 넣어 주세요.',
      returnNonNumeric: '연간 수익률을 숫자로 넣어 주세요.',
      syntax: '쉼표나 지수표기 없이 일반 숫자로 입력해 주세요.',
      pctRange: '-50에서 50 사이의 일반 백분율을 소수점 둘째 자리까지 입력해 주세요.',
    },
    states: {
      beyondLimit: '숫자가 이 도구가 안전하게 표시할 수 있는 범위보다 커져, 예상액을 보여줄 수 없어요. 더 작은 값이나 더 낮은 수익률 가정을 시도해 보세요.',
    },
    confirm: {
      heading: '이 계획을 저장할까요?',
      yourChoice: '이건 당신이 입력한 가정 아래에서 고른 계획이에요 \u2014 FinE Companion의 추천이나 예측이 아니에요.',
      confirm: '네, 저장할게요',
      cancel: '아직요',
      adopted: '내 계획에 저장됐어요. 언제든 다시 보거나, 수정하거나, 삭제할 수 있어요.',
    },
    replace: { heading: '지금 은퇴 계획을 바꿀까요?', body: '이미 저장된 은퇴 계획이 있어요. 이걸 저장하면 그 계획을 대신해요.', confirm: '바꿀게요', cancel: '기존 것 유지' },
    review: { heading: '저장된 은퇴 계획', note: '당신이 입력한 가정 아래에서 저장한 계획이에요. 여기서는 아무것도 바뀌지 않아요.', edit: '이 계획 수정', backToPlans: '내 계획으로 돌아가기', close: '닫기' },
    edit: { heading: '은퇴 계획 수정 중', note: '새로 저장하기 전까지 기존 계획은 그대로예요.' },
    noChangeNote: '현재와 계획한 매달 금액이 같아요 \u2014 그래도 이걸 은퇴 계획으로 저장할 수 있어요.',
    identicalNote: '저장된 계획이 이미 이 값과 가정에 정확히 일치해요. 새로 저장하려면 최소 한 가지를 바꿔 주세요.',
  },
}
